using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using System.Linq;

//Base classes for managing the agents healthbar and attribute window UI elements
public abstract class AgentUIManager : MonoBehaviour
{
    [SerializeField]
    protected float mPositionOffset;
    protected Canvas mCanvas;
    protected Camera mCamera;

    [SerializeField]
    protected GameObject mHealthBarPrefab;
    protected GameObject mHealthBar;
    protected Slider mHealthBarSlider;
    [SerializeField]
    protected GameObject mAttributeMenuPrefab;
    protected GameObject mAttributeMenu;
    [SerializeField]
    protected int mNumberOfAttributesToDisplay;

    protected void Awake()
    {
        mCanvas = FindObjectOfType<UIManager>().GetComponent<Canvas>();
        mCamera = Camera.main;
    }
    //Updates the health bar when displayed
    protected void UpdateHealthBar(float currentEnergy, float maxEnergy)
    {
        mHealthBar.transform.position = mCamera.WorldToScreenPoint(transform.gameObject.transform.position + Vector3.up * mPositionOffset);
        float percentageEnergyRemaining = currentEnergy / maxEnergy;
        mHealthBarSlider.value = percentageEnergyRemaining;
    }

    //Creates a new health bar and attribute menu object
    //The object could be created at the beginning for all actors but overhead of object pool was already high
    //Only one health bar and attribute are shown at a time and are generated by the player clicking an agent so will happen infrequently 
    protected void OnEnable()
    {
        mHealthBar = Instantiate(mHealthBarPrefab, mCanvas.transform);
        mAttributeMenu = Instantiate(mAttributeMenuPrefab, mCanvas.transform);
        mHealthBarSlider = mHealthBar.GetComponent<Slider>();
    }
    //Destroys healthbar when completed
    protected void OnDisable()
    {
        if (mHealthBar != null && mAttributeMenu != null)
        {
            Destroy(mHealthBar);
            Destroy(mAttributeMenu);
        }
    }

    private void Update()
    {
        UpdateAttributeText();
    }

    protected abstract void SetAttributeText();
    protected abstract void UpdateAttributeText();
}
